"""
Delivery client - SMTP digest sender + HMAC helpers for the /feedback endpoint.

Per ADR-0002, the Home Intelligence feedback loop uses user-supplied SMTP
and IMAP credentials directly. This module handles the outbound digest
via smtplib; inbox.py handles reply ingestion via imaplib.

The Message-ID is stamped with the reply_id so replies' In-Reply-To
header threads them back to the correct observation. An X-HI-Reply-Id
header and a [obs-<id>] subject tag act as fallbacks when a mail client
mangles the Message-ID.

The HMAC helpers here sign payloads for the plugin's own /feedback
endpoint (inbox.py posts signed payloads to it over localhost). The
secret is auto-generated by the plugin on first startup and not
user-configurable.
"""

import email.utils
import hashlib
import hmac
import json
import smtplib
import ssl
from email.message import EmailMessage
from typing import Optional


class DeliveryClient:
    def __init__(
        self,
        smtp_host: str,
        smtp_port: int,
        smtp_user: str,
        smtp_password: str,
        from_address: str,
        default_to: str,
        hmac_secret: str,
        logger,
        smtp_use_ssl: bool = True,
    ):
        self.smtp_host = smtp_host
        self.smtp_port = int(smtp_port or (465 if smtp_use_ssl else 587))
        self.smtp_user = smtp_user
        self.smtp_password = smtp_password
        self.from_address = from_address or smtp_user
        self.default_to = default_to
        self.hmac_secret = hmac_secret
        self.logger = logger
        self.smtp_use_ssl = smtp_use_ssl

    # ------------------------------------------------------------------
    # Outbound digest email
    # ------------------------------------------------------------------

    def send_email(
        self,
        subject: str,
        body_markdown: str,
        reply_id: Optional[str] = None,
        to: Optional[str] = None,
    ) -> Optional[str]:
        """Send the digest. Returns the Message-ID on success, None on failure."""
        recipient = to or self.default_to
        if not self._configured():
            self.logger.warning("SMTP not configured; digest email skipped")
            return None
        if not recipient:
            self.logger.warning("No digest recipient configured; digest email skipped")
            return None

        domain = self._sender_domain()
        msg = EmailMessage()
        msg["Subject"] = self._subject_with_tag(subject, reply_id)
        msg["From"] = self.from_address
        msg["To"] = recipient
        msg["Date"] = email.utils.formatdate(localtime=True)
        if reply_id:
            local = f"hi-{reply_id}-{email.utils.make_msgid().split('<', 1)[1].split('@', 1)[0]}"
            msg["Message-ID"] = f"<{local}@{domain}>"
            msg["X-HI-Reply-Id"] = reply_id
        else:
            msg["Message-ID"] = email.utils.make_msgid(domain=domain)
        msg.set_content(body_markdown)

        try:
            if self.smtp_use_ssl:
                ctx = ssl.create_default_context()
                with smtplib.SMTP_SSL(self.smtp_host, self.smtp_port, context=ctx, timeout=30) as s:
                    s.login(self.smtp_user, self.smtp_password)
                    s.send_message(msg)
            else:
                with smtplib.SMTP(self.smtp_host, self.smtp_port, timeout=30) as s:
                    s.starttls(context=ssl.create_default_context())
                    s.login(self.smtp_user, self.smtp_password)
                    s.send_message(msg)
        except Exception as exc:
            self.logger.exception(f"SMTP send failed: {exc}")
            return None

        message_id = msg["Message-ID"]
        self.logger.info(
            f"Digest sent: to={recipient} reply_id={reply_id} msgid={message_id}"
        )
        return message_id

    # ------------------------------------------------------------------
    # HMAC helpers for /feedback
    # ------------------------------------------------------------------

    def sign(self, payload: dict) -> str:
        raw = json.dumps(payload, separators=(",", ":"), sort_keys=True).encode("utf-8")
        return hmac.new(
            self.hmac_secret.encode("utf-8"), raw, hashlib.sha256
        ).hexdigest()

    def verify_signature(self, payload: dict, signature: Optional[str]) -> bool:
        if not signature or not self.hmac_secret:
            return False
        expected = self.sign(payload)
        return hmac.compare_digest(expected, signature)

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    def _configured(self) -> bool:
        return bool(self.smtp_host and self.smtp_user and self.smtp_password)

    def _sender_domain(self) -> str:
        addr = self.from_address or ""
        return addr.split("@", 1)[1] if "@" in addr else "localhost"

    @staticmethod
    def _subject_with_tag(subject: str, reply_id: Optional[str]) -> str:
        if not reply_id or f"[obs-{reply_id}]" in (subject or ""):
            return subject
        return f"{subject} [obs-{reply_id}]"
